[proxies]
proxy1 ansible_host=10.211.89.105 keepalived_state=MASTER keepalived_priority=101
proxy2 ansible_host=10.211.89.22  keepalived_state=BACKUP keepalived_priority=100

[k8s_master]
k8s-master ansible_host=10.211.89.190 ansible_python_interpreter=/usr/bin/python3

[k8s_workers]
k8s-worker1 ansible_host=10.211.89.193 ansible_python_interpreter=/usr/bin/python3
k8s-worker2 ansible_host=10.211.89.174 ansible_python_interpreter=/usr/bin/python3

[k8s:children]
k8s_master
k8s_workers

[all_nodes:children]
proxies
k8s

[all_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=yes
ansible_become_method=sudo
