---
keepalived_state: "BACKUP"
keepalived_priority: 100
keepalived_vip: "{{ shared_vip_address }}" 
keepalived_smtp_server: "127.0.0.1"
keepalived_smtp_connect_timeout: 30
keepalived_email_to: "admin@example.com"
